# Generated by Django 3.1.5 on 2021-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=25)),
                ('classgroup', models.CharField(max_length=10, null=True)),
                ('has_evaluated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=19)),
                ('level', models.CharField(max_length=25)),
                ('classgroup', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('item3', models.IntegerField()),
                ('item4', models.IntegerField()),
                ('item5', models.IntegerField()),
                ('opinion', models.CharField(max_length=280, null=True)),
            ],
        ),
    ]
