# Generated by Django 3.1.5 on 2021-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('has_evaluated', models.BooleanField(default=False)),
                ('evaluation_timestamp', models.CharField(max_length=19, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='has_evaluated',
        ),
    ]
