# Generated by Django 3.1.5 on 2021-02-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210205_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentevaluation',
            name='has_evaluated',
        ),
    ]
